# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - bluefield
  always: true

trigger: none

pr:
  branches:
    include:
      - bluefield
  paths:
    exclude:
      - .github

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: buildimage
    type: github
    name: nvidia-sonic/sonic-buildimage
    endpoint: nvidia-sonic
    ref: bluefield

variables:
- template: .azure-pipelines/azure-pipelines-repd-build-variables.yml@buildimage
- template: .azure-pipelines/template-variables.yml@buildimage
- name: CACHE_MODE
  value: rcache
- name: ENABLE_FIPS
  value: y

stages:
- stage: Build
  dependsOn: []
  jobs:
  - template: .azure-pipelines/azure-pipelines-build.yml
    parameters:
      buildOptions: 'USERNAME=admin SONIC_BUILD_JOBS=$(nproc) ${{ variables.VERSION_CONTROL_OPTIONS }}'
      preSteps:
      - task: InstallSSHKey@0
        displayName: 'Install an SSH key'
        inputs:
          knownHostsEntry: '$(myHostsEntry)'
          sshPublicKey: '$(myPubKey)'
          sshKeySecureFile: 'id_rsa'
      jobGroups:
      - name: nvidia-bluefield
        pool: sonicbld-arm64
        timeoutInMinutes: 2880
        variables:
          pxe_image: yes
          bfb_image: yes
          PLATFORM_ARCH: arm64


