ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sd_low_power_mode_global_default: "true"
    sku: "configs/sku/innovium.77700_A"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    mac_clk: "1340"
    skip_pll_check: "false"
    sys_clk: "1720"
    mbist_on_init: "true"
    ifc_clk: "1200"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    ecn_stats_enable: "1"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - id: "89"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "11"
    speed: "400G"
    sysport: "89"
    type: "eth"
  - id: "81"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "10"
    speed: "400G"
    sysport: "81"
    type: "eth"
  - id: "73"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "9"
    speed: "400G"
    sysport: "73"
    type: "eth"
  - id: "65"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "8"
    speed: "400G"
    sysport: "65"
    type: "eth"
  - id: "57"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "7"
    speed: "400G"
    sysport: "57"
    type: "eth"
  - id: "49"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "6"
    speed: "400G"
    sysport: "49"
    type: "eth"
  - id: "41"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "5"
    speed: "400G"
    sysport: "41"
    type: "eth"
  - id: "33"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "4"
    speed: "400G"
    sysport: "33"
    type: "eth"
  - id: "153"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "19"
    speed: "400G"
    sysport: "153"
    type: "eth"
  - id: "145"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "18"
    speed: "400G"
    sysport: "145"
    type: "eth"
  - id: "137"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "17"
    speed: "400G"
    sysport: "137"
    type: "eth"
  - id: "129"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "16"
    speed: "400G"
    sysport: "129"
    type: "eth"
  - id: "121"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "15"
    speed: "400G"
    sysport: "121"
    type: "eth"
  - id: "113"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "14"
    speed: "400G"
    sysport: "113"
    type: "eth"
  - id: "105"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "13"
    speed: "400G"
    sysport: "105"
    type: "eth"
  - id: "97"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "12"
    speed: "400G"
    sysport: "97"
    type: "eth"
  - id: "209"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "26"
    speed: "400G"
    sysport: "209"
    type: "eth"
  - id: "217"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "27"
    speed: "400G"
    sysport: "217"
    type: "eth"
  - id: "193"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "24"
    speed: "400G"
    sysport: "193"
    type: "eth"
  - id: "201"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "25"
    speed: "400G"
    sysport: "201"
    type: "eth"
  - id: "177"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "22"
    speed: "400G"
    sysport: "177"
    type: "eth"
  - id: "185"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "23"
    speed: "400G"
    sysport: "185"
    type: "eth"
  - id: "161"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "20"
    speed: "400G"
    sysport: "161"
    type: "eth"
  - id: "169"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "21"
    speed: "400G"
    sysport: "169"
    type: "eth"
  - id: "17"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "2"
    speed: "400G"
    sysport: "17"
    type: "eth"
  - id: "25"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "3"
    speed: "400G"
    sysport: "25"
    type: "eth"
  - id: "1"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "0"
    speed: "400G"
    sysport: "1"
    type: "eth"
  - id: "9"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "1"
    speed: "400G"
    sysport: "9"
    type: "eth"
  - id: "241"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "30"
    speed: "400G"
    sysport: "241"
    type: "eth"
  - id: "249"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "31"
    speed: "400G"
    sysport: "249"
    type: "eth"
  - id: "225"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "28"
    speed: "400G"
    sysport: "225"
    type: "eth"
  - id: "233"
    fec: "KPFEC"
    lanes: "0:8"
    serdes_group: "29"
    speed: "400G"
    sysport: "233"
    type: "eth"
  - id: "257"
    fec: "NONE"
    lanes: "0:1"
    serdes_group: "32"
    speed: "10G"
    sysport: "257"
    type: "mgmt 0"
  - id: "258"
    fec: "NONE"
    lanes: "1:1"
    serdes_group: "32"
    speed: "10G"
    sysport: "258"
    type: "mgmt 1"
  isg:
  - id: "11"
    lane_swap: "27163504"
    rx_polarity: "01010000"
    tx_polarity: "01100000"
  - id: "10"
    lane_swap: "51604372"
    rx_polarity: "11001000"
    tx_polarity: "11110000"
  - id: "9"
    lane_swap: "17032546"
    rx_polarity: "10001000"
    tx_polarity: "00000100"
  - id: "8"
    lane_swap: "70435162"
    rx_polarity: "11000100"
    tx_polarity: "00100101"
  - id: "7"
    lane_swap: "27053416"
    rx_polarity: "00011001"
    tx_polarity: "10001000"
  - id: "6"
    lane_swap: "70635142"
    rx_polarity: "10001000"
    tx_polarity: "01100001"
  - id: "5"
    lane_swap: "27053416"
    rx_polarity: "00001001"
    tx_polarity: "00001000"
  - id: "4"
    lane_swap: "62405173"
    rx_polarity: "11000101"
    tx_polarity: "10110000"
  - id: "19"
    lane_swap: "06152347"
    rx_polarity: "11010110"
    tx_polarity: "10001110"
  - id: "18"
    lane_swap: "73614052"
    rx_polarity: "11001100"
    tx_polarity: "11100001"
  - id: "17"
    lane_swap: "17053426"
    rx_polarity: "10001001"
    tx_polarity: "00001000"
  - id: "16"
    lane_swap: "54216073"
    rx_polarity: "10000011"
    tx_polarity: "01001010"
  - id: "15"
    lane_swap: "36072514"
    rx_polarity: "10100000"
    tx_polarity: "10100001"
  - id: "14"
    lane_swap: "50763241"
    rx_polarity: "00010001"
    tx_polarity: "01110001"
  - id: "13"
    lane_swap: "26071435"
    rx_polarity: "00000011"
    tx_polarity: "00101001"
  - id: "12"
    lane_swap: "43510627"
    rx_polarity: "11100100"
    tx_polarity: "00011101"
  - id: "26"
    lane_swap: "31427506"
    rx_polarity: "10011000"
    tx_polarity: "11110001"
  - id: "27"
    lane_swap: "21735406"
    rx_polarity: "01011110"
    tx_polarity: "10011100"
  - id: "24"
    lane_swap: "07162435"
    rx_polarity: "10010000"
    tx_polarity: "10001010"
  - id: "25"
    lane_swap: "64501372"
    rx_polarity: "11010001"
    tx_polarity: "10001010"
  - id: "22"
    lane_swap: "35071624"
    rx_polarity: "00100011"
    tx_polarity: "11001011"
  - id: "23"
    lane_swap: "64705132"
    rx_polarity: "11010100"
    tx_polarity: "11101000"
  - id: "20"
    lane_swap: "16270453"
    rx_polarity: "00101100"
    tx_polarity: "00001001"
  - id: "21"
    lane_swap: "71356204"
    rx_polarity: "01100010"
    tx_polarity: "00001011"
  - id: "2"
    lane_swap: "37260145"
    rx_polarity: "10011010"
    tx_polarity: "11000000"
  - id: "3"
    lane_swap: "47512630"
    rx_polarity: "10010100"
    tx_polarity: "10101101"
  - id: "0"
    lane_swap: "05462713"
    rx_polarity: "01000000"
    tx_polarity: "10010010"
  - id: "1"
    lane_swap: "71605432"
    rx_polarity: "00000000"
    tx_polarity: "11000101"
  - id: "30"
    lane_swap: "37251604"
    rx_polarity: "11000010"
    tx_polarity: "11001000"
  - id: "31"
    lane_swap: "42736051"
    rx_polarity: "10000110"
    tx_polarity: "01000010"
  - id: "28"
    lane_swap: "01245736"
    rx_polarity: "10110101"
    tx_polarity: "10000001"
  - id: "29"
    lane_swap: "52706134"
    rx_polarity: "00010010"
    tx_polarity: "10101010"
